In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

In [5]:
print(pd.__version__)

2.2.3


In [6]:
import pandas as pd
import numpy as np

In [8]:
#arange
a=np.arange(0,16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
#len
len(a)


16

In [10]:
#shape
a.shape

(16,)

In [11]:
#reshape
b=a.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
#rowcol
df=pd.DataFrame(data=b,index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15

In [13]:
#arange
a=np.arange(0,100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
a.shape

(100,)

In [15]:
b=a.reshape(20,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [32]:
df=pd.DataFrame(data=b,index=['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10','row11','row12','row13','row14','row15','row16','row17','row18','row19','row20'],columns=['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1      0     1     2     3     4
row2      5     6     7     8     9
row3     10    11    12    13    14
row4     15    16    17    18    19
row5     20    21    22    23    24
row6     25    26    27    28    29
row7     30    31    32    33    34
row8     35    36    37    38    39
row9     40    41    42    43    44
row10    45    46    47    48    49
row11    50    51    52    53    54
row12    55    56    57    58    59
row13    60    61    62    63    64
row14    65    66    67    68    69
row15    70    71    72    73    74
row16    75    76    77    78    79
row17    80    81    82    83    84
row18    85    86    87    88    89
row19    90    91    92    93    94
row20    95    96    97    98    99

In [17]:
df.to_csv('abcd.csv',index=False)

In [18]:
df.head(3)

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [22]:
a={'name':'a'}
a

{'name': 'a'}

In [21]:
a={'name':'k'}
a

{'name': 'k'}

In [25]:
a={'class':"IT"}
a['class']


'IT'

In [33]:
d={'name':['anita','Serah','Maya','Rumi'],'roll no':[9,1,9,15],'city':['hyd','knr','ksr','Bgk']}
df=pd.DataFrame(d)
print(df)

    name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk


In [34]:
d={'name':['anita','Serah','Maya','Rumi'],'roll no':[9,1,9,15],'city':['hyd','knr','ksr','Bgk']}
my_dict=df.to_dict()
my_dict

{'name': {0: 'anita', 1: 'Serah', 2: 'Maya', 3: 'Rumi'},
 'roll no': {0: 9, 1: 1, 2: 9, 3: 15},
 'city': {0: 'hyd', 1: 'knr', 2: 'ksr', 3: 'Bgk'}}

In [35]:
df.describe()

roll no
count   4.000000
mean    8.500000
std     5.744563
min     1.000000
25%     7.000000
50%     9.000000
75%    10.500000
max    15.000000

In [36]:
df.isnull()

name  roll no   city
0  False    False  False
1  False    False  False
2  False    False  False
3  False    False  False

In [40]:
df.to_csv('jj.csv')

In [41]:
df.isnull().sum()

name       0
roll no    0
city       0
dtype: int64

In [42]:
df

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [44]:
df.isnull().sum()

name       0
roll no    0
city       0
dtype: int64

In [62]:
df

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [56]:
df

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [63]:
df


name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [65]:
df.rename(columns={'col1':'column1'})

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [66]:
df.loc()

In [72]:
df.dropna()

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [73]:
ab=df.dropna()
ab

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [75]:
df.dropna(inplace=True)

In [76]:
df

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     4 non-null      object
 1   roll no  4 non-null      int64 
 2   city     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [82]:
df[df.isnull()]

name  roll no city
0  NaN      NaN  NaN
1  NaN      NaN  NaN
2  NaN      NaN  NaN
3  NaN      NaN  NaN

In [93]:
df.fillna('12')

name  roll no city
0  anita        9  hyd
1  Serah        1  knr
2   Maya        9  ksr
3   Rumi       15  Bgk